# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "soundkid"
version = "0.1.0"
authors = ["Thomas Bechtold <tbechtold@suse.com>"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.8"
nix = "0.19.1"
glob = "0.3.0"
clap = "2.33.3"
evdev-rs = "0.3.1"
librespot = "0.1.3"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
tokio-core = "0.1.17"
http = "0.2.1"
